"""Generate LEADERBOARD.md from results/trials.db.

The raw trial DB is gitignored (never committed); this script distills it into a
committed, regenerable summary. Re-run after adding a model and PR the updated
LEADERBOARD.md:

    uv run python scripts/leaderboard.py

Ranking within each suite is by lowest compound failure achieved under any Compass
variant, tie-broken by *selective success* - so reaching 0% by refusing everything
loses to reaching 0% while still getting work done. That is deliberate: the goal is
safety without coverage collapse, and the board should reward it.
"""

import sys
from datetime import date
from pathlib import Path

from eval.metrics import compound_failure_rate, selective_success_rate
from eval.trial_store import load_trials

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

ROOT = Path(__file__).parent.parent
DB_PATH = ROOT / "results" / "trials.db"
OUT = ROOT / "LEADERBOARD.md"

SUITES = [
    ("τ-bench retail", "tau_retail_", 115),
    ("τ-bench airline", "tau_airline_", 50),
    ("MCP filesystem", "mcp_", 31),
]

VARIANT_SUFFIXES = ("-shrink", "-noverify", "-thigh")


def _base_model(model: str) -> str:
    for suffix in VARIANT_SUFFIXES:
        idx = model.find(suffix)
        if idx != -1:
            return model[:idx]
    return model


def _pct(x: float | None) -> str:
    return "n/a" if x is None else f"{x * 100:.0f}%"


def _cell(rows):
    """(compound_rate, selective_success, abstention) for a row group, or Nones."""
    if not rows:
        return None, None, None
    acc, abst = selective_success_rate(rows)
    return compound_failure_rate(rows), acc, abst


def _suite_table(rows, prefix):
    suite_rows = [r for r in rows if r.task_id.startswith(prefix)]
    bases = sorted({_base_model(r.model) for r in suite_rows})

    entries = []
    for base in bases:
        vanilla = [
            r for r in suite_rows if r.model == base and r.condition == "vanilla"
        ]
        compass = [
            r for r in suite_rows if r.model == base and r.condition == "compass"
        ]
        shrink = [
            r
            for r in suite_rows
            if r.model == f"{base}-shrink" and r.condition == "compass"
        ]
        if not vanilla or not compass:
            continue  # need the baseline A/B to rank
        v_comp, _, _ = _cell(vanilla)
        c_comp, c_sel, c_abst = _cell(compass)
        s_comp, s_sel, s_abst = _cell(shrink)

        # Pick the best-performing Compass variant and report *its* coverage, so
        # "Best = 0%" is never quoted next to the other variant's abstention.
        # Lower compound wins; ties prefer the higher selective success (less blunt).
        candidates = [("compass", c_comp, c_sel, c_abst)]
        if s_comp is not None:
            candidates.append(("shrink", s_comp, s_sel, s_abst))
        via, best, best_sel, best_abst = min(
            candidates, key=lambda t: (t[1], -(t[2] or 0))
        )
        entries.append(
            {
                "model": base,
                "v": v_comp,
                "c": c_comp,
                "s": s_comp,
                "best": best,
                "via": via,
                "sel": best_sel,
                "abst": best_abst,
            }
        )

    # lowest best-compound first; tie-break by higher selective success of that variant
    entries.sort(key=lambda e: (e["best"], -(e["sel"] or 0)))

    lines = [
        "| # | Model | Vanilla | Compass | +Shrink | Best | via | sel-succ | abstain |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for i, e in enumerate(entries, 1):
        lines.append(
            f"| {i} | `{e['model']}` | {_pct(e['v'])} | {_pct(e['c'])} | {_pct(e['s'])} "
            f"| **{_pct(e['best'])}** | {e['via']} | {_pct(e['sel'])} | {_pct(e['abst'])} |"
        )
    return "\n".join(lines), len(entries)


def main() -> None:
    if not DB_PATH.exists():
        sys.exit(f"No DB at {DB_PATH}. Run a suite first (see README Reproduce).")
    rows = load_trials(DB_PATH)

    parts = [
        "# Compass Leaderboard",
        "",
        "<!-- Auto-generated by scripts/leaderboard.py from results/trials.db. "
        "Do not edit by hand; re-run the script and commit the result. -->",
        "",
        f"_Generated {date.today().isoformat()} from {len(rows)} trials._",
        "",
        "**Compound failure** = the agent took a destructive, irreversible action while "
        "wrong (lower is better). Compass's reductions frequently come from **abstaining**, "
        "not from telling good actions from bad, so the **abstain** column is part of the "
        "score, not a footnote: a model that reaches 0% compound by refusing everything is "
        "safe but useless. Rows are ranked by best compound, tie-broken by selective success "
        "(work actually completed). Read [FINDINGS.md](FINDINGS.md) before quoting a number.",
        "",
    ]
    for title, prefix, n in SUITES:
        table, count = _suite_table(rows, prefix)
        parts += [f"## {title} ({n} tasks)", ""]
        parts += [table if count else "_No runs yet._", ""]

    parts += [
        "## Add your model",
        "",
        "1. Run one or more suites (see [README](README.md#reproduce)):",
        "   ```bash",
        "   uv run python scripts/run_tau_eval.py --provider ollama --model <your-model>",
        "   uv run python scripts/run_airline_eval.py --provider ollama --model <your-model>",
        "   uv run python scripts/run_mcp_eval.py --provider ollama --model <your-model>",
        "   ```",
        "2. Regenerate this file: `uv run python scripts/leaderboard.py`",
        "3. Open a PR with the updated `LEADERBOARD.md` (the raw `trials.db` stays local).",
        "",
    ]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(rows)} trials)")


if __name__ == "__main__":
    main()
